config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  resources :foods
  resources :reviews
  root "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :reviews



  mount_uploader :image, ImageUploader
end

app/models/image.rb
class Image < ActiveRecord::Base
  # validates_processing_of :image
  belongs_to :food

  mount_uploader :image, ImageUploader
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :food
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  has_many :foods
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @food = Food.all

  end

  def new
    @foods = Food.new
  end

  def create
    food = current_user.foods.build(food_params)
    if food.save!
      redirect_to foods_path
    else
      redirect_to new_food_paths
    end
  end

  def show
    @food = Food.find(params[:id])
    @review = Review.where(params[:id])
  end

  def edit
  end

  private
    def food_params
      params.require(:food).permit(:food_name,:user_id, :food_type, :food_description, :food_review, :food_original_score, :location, :image)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @review = Review.all

  end

  def new
    @review = Review.new
  end

  def create

    review = Review.new(reviewPermit)
    review.user_id = current_user.id
    review.food_id = params[:review][:food_id]
    if review.save!
      redirect_to foods_path
    else
      redirect_to new_review_path
    end
  end

  def show
    @reviews = Review.find(params[:id])

  end

  def edit
  end

  private
  def reviewPermit
    params.require(:review).permit(:review, :score, :user_id, :food_id)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @user = current_user
    @review = Food.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/foods/edit.html.erb
<h1>Foods#edit</h1>
<p>Find me in app/views/foods/edit.html.erb</p>

app/views/foods/index.html.erb
<div class="food-list-header">
  <h1>Foods list</h1>
</div>

  <% @food.each do |f| %>
  <div class="index-wrapper">
    <a href="/foods/<%= f.id %>">
    <% if f.image.thumb.url == nil%>
      <div> <img class="image-food" id="food-image" alt=""> </div>
      <% else %>
      <div> <img class="image-food" src="<%= f.image.thumb.url %>" alt=""> </div>
    <% end %>
    <div class="food-decription">
      <div class=""> <a href="/foods/<%= f.id %>"><strong>Food:</strong> <%= f.food_name %> </a> </div>
      <div><strong>Type:</strong><%= f.food_type %></div>
      <div class=""><strong>location:</strong> <%= f.location %></div>

    </div>
    </a>
  </div>
<strong></strong>  <% end %>

app/views/foods/new.html.erb
<div class="food-breakdown">
  <h1>Yum new food what is it?</h1>
</div>

<%= form_for Food.new do |f|%>
  <div class="">
    <div class="food-breakdown">
      Food: <%= f.text_field :food_name%>
    </div>
    <div class="hr">
      <hr>
    </div>
    <div class="food-breakdown">
      Food type: <%= f.text_field :food_type%>
    </div>
    <div class="hr">
      <hr>
    </div>
    <div class="food-breakdown">
      Food description: <%= f.text_field :food_description%>
    </div>
    <div class="hr">
      <hr>
    </div>
    <div class="food-breakdown">

      location: <%= f.text_field :location, id: "pac-input", class: "controls", type: "text", placeholder: "Search Box" %>
      <%= hidden_field :location, value: @location %>

      <div id="map"></div>
    </div>
    <div class="hr">
      <hr>
    </div>
    <div class="food-breakdown">
      Food review: <%= f.text_area :food_review%>
    </div>
    <div class="hr">
      <hr>
    </div>
    <div class="food-breakdown">
      Food score: <%= f.select :food_original_score, [1,2,3,4,5,6,7,8,9,10]%>
    </div>

    <div class="food-breakdown">
      <%= f.file_field :image %>
      <% if f.object.image? %>
      <%= image_tag f.object.image.thumb.url %>
      <% end %>
    </div>




  </div>
  <div class="food-breakdown">
    <%= f.submit%>
  </div>

<% end %>




<script>
// This example adds a search box to a map, using the Google Place Autocomplete
// feature. People can enter geographical searches. The search box will return a
// pick list containing a mix of places and predicted search terms.

// This example requires the Places library. Include the libraries=places
// parameter when you first load the API. For example:
// <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

function initAutocomplete() {
var map = new google.maps.Map(document.getElementById('map'), {
center: {lat: 39.9526, lng: -75.1652},
zoom: 13,
mapTypeId: 'roadmap'
});

// Create the search box and link it to the UI element.
var input = document.getElementById('pac-input');
var searchBox = new google.maps.places.SearchBox(input);
map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

// Bias the SearchBox results towards current map's viewport.
map.addListener('bounds_changed', function() {
searchBox.setBounds(map.getBounds());
});

var markers = [];
// Listen for the event fired when the user selects a prediction and retrieve
// more details for that place.
searchBox.addListener('places_changed', function() {
var places = searchBox.getPlaces();

if (places.length == 0) {
  return;
}

// Clear out the old markers.
markers.forEach(function(marker) {
  marker.setMap(null);
});
markers = [];

// For each place, get the icon, name and location.
var bounds = new google.maps.LatLngBounds();
places.forEach(function(place) {
  if (!place.geometry) {
    console.log("Returned place contains no geometry");
    return;
  }
  var icon = {
    url: place.icon,
    size: new google.maps.Size(71, 71),
    origin: new google.maps.Point(0, 0),
    anchor: new google.maps.Point(17, 34),
    scaledSize: new google.maps.Size(25, 25)
  };


  // Create a marker for each place.
  markers.push(new google.maps.Marker({
    map: map,
    icon: icon,
    title: place.name,
    position: place.geometry.location
  }));

  if (place.geometry.viewport) {
    // Only geocodes have viewport.
    bounds.union(place.geometry.viewport);
  } else {
    bounds.extend(place.geometry.location);
  }
});
console.log(markers)
map.fitBounds(bounds);
});
}

</script>

app/views/foods/show.html.erb
<div class="food-name">
  <div class="">

    <% if  @food.image.thumb.url == nil%>
     <p> Ah there's no image</p>
    <% else %>
      <div class="">
        <%= image_tag @food.image.thumb.url, :class => 'show-image' %>
      </div>
    <% end %>
  </div>

    <h1><%= @food.food_name %></h1>

  <p>Review by: <%= @food.id %></p>

  <div class="hr">
    <hr>
  </div>
  <div class="food-breakdown">
    <strong>Food type:</strong> <%= @food.food_type %>
  </div>


  <div class="hr">
    <hr>
  </div>
  <div class="food-breakdown">
    <strong>Description:</strong> <%= @food.food_description %>
  </div>

  <div class="hr">
    <hr>
  </div>
  <div class="food-breakdown">
    <strong>Review:</strong> <%= @food.food_review %>
  </div>
  <div class="hr">
    <hr>
  </div>
  <div class="food-breakdown">
    <strong>Location:</strong> <%= @food.location %>
  </div>
</div>
<div id="map" value=" <%= @food.location %> "></div>
<input id="pac-input" class="controls" type="text" value=" <%= @food.location %> ">

<br>

<% if signed_in?%>
<h2>Different option? leave review and score for others to see</h2>

<%=link_to 'Create review', new_review_path(:food_id => @food.id) %>
<% end %>

<% @review.each do |r|%>

    <% if r.food_id == @food.id %>
    <div class="">
      <div class="">
        <strong>Review:</strong> <%= r.review%>
      </div>
      <div class="">
        <strong>Score:</strong> <%= r.score%>
      </div>
      <hr>
    </div>

    <% end %>
<% end %>

<script>

// This example adds a search box to a map, using the Google Place Autocomplete
// feature. People can enter geographical searches. The search box will return a
// pick list containing a mix of places and predicted search terms.

// This example requires the Places library. Include the libraries=places
// parameter when you first load the API. For example:
// <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

function initAutocomplete() {
var map = new google.maps.Map(document.getElementById('map'), {
center: {lat: 39.9526, lng: -75.1652},
zoom: 13,
mapTypeId: 'roadmap'
});

// Create the search box and link it to the UI element.
var input = document.getElementById('pac-input');
var searchBox = new google.maps.places.SearchBox(input);
map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

// Bias the SearchBox results towards current map's viewport.
map.addListener('bounds_changed', function() {
searchBox.setBounds(map.getBounds());
});

var markers = [];
// Listen for the event fired when the user selects a prediction and retrieve
// more details for that place.
searchBox.addListener('places_changed', function() {
var places = searchBox.getPlaces();

if (places.length == 0) {
  return;
}

// Clear out the old markers.
markers.forEach(function(marker) {
  marker.setMap(null);
});
markers = [];

// For each place, get the icon, name and location.
var bounds = new google.maps.LatLngBounds();
places.forEach(function(place) {
  if (!place.geometry) {
    console.log("Returned place contains no geometry");
    return;
  }
  var icon = {
    url: place.icon,
    size: new google.maps.Size(71, 71),
    origin: new google.maps.Point(0, 0),
    anchor: new google.maps.Point(17, 34),
    scaledSize: new google.maps.Size(25, 25)
  };


  // Create a marker for each place.
  markers.push(new google.maps.Marker({
    map: map,
    icon: icon,
    title: place.name,
    position: place.geometry.location
  }));

  if (place.geometry.viewport) {
    // Only geocodes have viewport.
    bounds.union(place.geometry.viewport);
  } else {
    bounds.extend(place.geometry.location);
  }
});
console.log(markers)
map.fitBounds(bounds);
});
}

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kritique</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style media="screen">
    /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 400px;
        width: 100%;
      }
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
      #description {
        font-family: Roboto;
        font-size: 15px;
        font-weight: 300;
      }

      #infowindow-content .title {
        font-weight: bold;
      }

      #infowindow-content {
        display: none;
      }

      #map #infowindow-content {
        display: inline;
      }

      .pac-card {
        margin: 10px 10px 0 0;
        border-radius: 2px 0 0 2px;
        box-sizing: border-box;
        -moz-box-sizing: border-box;
        outline: none;
        box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);
        background-color: #fff;
        font-family: Roboto;
      }

      #pac-container {
        padding-bottom: 12px;
        margin-right: 12px;
      }

      .pac-controls {
        display: inline-block;
        padding: 5px 11px;
      }

      .pac-controls label {
        font-family: Roboto;
        font-size: 13px;
        font-weight: 300;
      }

      #pac-input {
        background-color: #fff;
        font-family: Roboto;
        font-size: 15px;
        font-weight: 300;
        margin-left: 12px;
        padding: 0 11px 0 13px;
        text-overflow: ellipsis;
        width: 400px;
      }

      #pac-input:focus {
        border-color: #4d90fe;
      }

      #title {
        color: #fff;
        background-color: #4d90fe;
        font-size: 25px;
        font-weight: 500;
        padding: 6px 12px;
      }
      #target {
        width: 345px;
      }
    </style>

  </head>

  <body>
    <!-- navbar  -->
    <div class="navbar-border">
      <div class="nav-button">
        <%= link_to "Home", root_path%>
      </div>
      <% if !signed_in? %>
        <div class="nav-button">
          <%= link_to 'sign in', new_user_session_path%>
        </div>
        <div class="nav-button">
          <%= link_to 'sign up', new_user_registration_path%>
        </div>

      <% else signed_in? %>
      <div class="nav-button">

      </div>
      <div class="nav-button">
        <%= link_to "Food list", foods_path%>
      </div>
        <div class="nav-button">
          <%= link_to "create new food entry", new_food_path%>
        </div>
        <div class="nav-button">
          <%= link_to "sign out", destroy_user_session_path, :method => :delete%>
        </div>
      <% end %>
    </div>


    <%= yield %>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCtw8zemjx0wGvN8igQaXtu5Pyx_Iwvofw&libraries&libraries=places&callback=initAutocomplete" async defer></script>

    <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>

<% @review.each do |r|%>

  <div class="">
    <div class="">
      <strong> Review:</strong> <%= r.review %>
    </div>
    <br>

    <div class="">
      <strong>Score:</strong> <%= r.score%>
    </div>

    <div class="">
      <strong>User:</strong> <%= r.user_id%>
    </div>

    <div class="">
      <strong>Date:</strong> <%= r.created_at%>
    </div>

    <hr>

  </div>
<% end %>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>



<%= form_for Review.new do |r|%>
  <div class="">
    Leave a review<%= r.text_area :review %>
  </div>
  <div class="">
    Give a score<%= r.text_field :score %>
  </div>

<%= r.hidden_field :food_id, value: @food_id %>
<%= r.submit%>
<% end %>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/welcome/index.html.erb
<div class="top-navbar">
  <div class='background-image'>
    <!-- beginning of left side brand banner -->
    <div class="brand-wrapper">
      <div class="brand-logo"></div>
      <div class="branding">
        Kritique
      </div>
    </div>

    <!-- beginning of tag line -->

      <div class="tagline-wrapper">
        <div class="tagline">
          <h2>Real Reviews</h2>
        </div>
        <div class="tagline">
          <h2>By Real People</h2>
        </div>
      </div>
  </div>
</div>

<div class="Critique-explained">
  <div class="what-is-Kritique">
    <h1>What is Kritique?</h1>
  </div>
  <div class="what">
    <div class="what-1" id="what-content-1">
      <h2>Kritique is a platform that allows uses to have a level of <br> transparentcy to the food we not only order and eat.</h2>
    </div>
    <div class="what-1" id='image-1'></div>

    <div class="what-1" id='image-2'></div>
    <div class="what-1" id="what-content-2">
      <h2>Kritique is the platform that takes food reviwing and blogging to the next level, <br>  with the added benefit of leaving your own spin to what you thought of the meal</h2>
    </div>

  </div>
</div>





<div class="">
  <% if signed_in?%>
  hello <%= @user.email%>!
  <% end %>
</div>

<div class="">

</div>

<!-- <input id="pac-input" class="controls" type="text" placeholder="Search Box">
    <div id="map"></div> -->